### ISSUE TITLE
Missing config for Witti Prysm beacon

### ISSUE THREAD

**Issue by handelaar2** [goerli/witti#11]
The Prysm beacon config only shows --web3provider ws://127.0.0.1:8546 \
This is incomplete as currently Prysm uses both ws and http.

Only specifying the above can lead to issues, as the http parameter will default to "https://goerli.prylabs.net"
(resulting in 2 different eth1 sources potentially being different)

So if you specify localhost on port 8546, you also have to specify:
`--http-web3provider="http://127.0.0.1:8545" \` 

Details around issues in Prysm rep : https://github.com/prysmaticlabs/prysm/issues/5826

Below a screen print of the Prysm witti config:

![2020-05-27_11-37-28](https://user-images.githubusercontent.com/28559038/83004097-83897a00-a00f-11ea-9b2f-849728991007.png)

**Comment by q9f** [comment]
damn, I thought one API is enough. why would it require both??

**Comment by handelaar2** [comment]
Websocket gives performance issue->switch to http for past logs (https://github.com/prysmaticlabs/prysm/issues/2295)
result:
last logs: http
future logs: ws subscription

#5826 initiates a change (hopefully) to http only.
(see discussion at bottom of issue)

**Comment by handelaar2** [comment]
Not sure fit this will work. It now says:
--http-web3provider ws://127.0.0.1:8545 \

should be:
--http-web3provider **http**://127.0.0.1:8545 \

**Comment by torfbolt** [comment]
Can confirm that it does **not** work with ws:// instead of http://
