### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by canbal99** [goerli/witti#20]
Today I have seen 8 logs related with this problem with this tag "PLEASE FIX OR REPORT"

[teku.log](https://github.com/goerli/witti/files/4776199/teku.log)

**Comment by djrtwo** [comment]
I recommend bring this to the teku repo -- https://github.com/pegasyseng/teku

Also, teku has had memory problems when the chain doesn't finalize. Looks like you ran out of memory

**Comment by canbal99** [comment]
sure, i will move it there...
