### ISSUE TITLE
Depositing to contract

### ISSUE THREAD

**Issue by Youllneverknow0** [goerli/witti#6]
Hello,

this is more an issue of documentation and understanding I think rather then a technical issue.
I mananged to contriubute in the testnet5 and would like to do it in the schlesi testnet as well.

Geth is running properly,
lighthouse is properly running a beacon node
I have a MetaMask wallet with >32 ETH.

The only thing I do not get is how I "sign and use the contract" as a validator. There is a section that tries to explain the procedure. However, it's not entirely clear to me:

As far as I understood I need to send 32 ETH to 0xA15554BF93a052669B511ae29EA21f3581677ac5. But I cannot see how I do this with that line:

lighthouse account validator new \
--send-deposits \
--password ./password.txt \
--deposit-value 3200000000 random

For my understanding there is no parameter for the destination (contract address). 
- So how does lighthouse know where to send the GörliETH to?
Moreover there is no adress from my wallet (source).
- So how does lighthouse know where to send the GörliETH from?

And also my questions are:

- How would I send additional GörliETH to the contract if I wanted to?
- How would I withdraw GörliETH from the contract if I wanted to?
- Where can see the current deposite of GörliETH I made for the contract?

I do have a lack of knowledge here.
I appreciate your help.

Thank you

**Comment by q9f** [comment]
Please hold on for now, Schlesi is currently down and will be replaced as soon as possible.

The commands for deposits changed a little bit, I'll document this in more detail.

You can take a peak here: https://github.com/goerli/schlesi/tree/master/lighthouse
