### ISSUE TITLE
Witti boot enr have 0.0.0.0 address

### ISSUE THREAD

**Issue by paulhauner** [goerli/witti#7]
When addressing https://github.com/sigp/lighthouse/issues/1186, I attempted to connect to Witti to verify LH could sync. I noticed that the [boot ENR](https://github.com/goerli/witti/blob/master/lighthouse/boot_enr.yaml) have a `0.0.0.0` address:

```
enr-cli --enr "enr:-
KG4QO6QrRlWQ2Z5ss4XoUsrPvsepRuuogcHyC81gMQr7PJ3IFh41bDnGSl9iN_ijg2EgQeEQDpRPkE4FzD2ecbp6XoChGV0aDKQgGboQQAAARP__________4JpZIJ2NIJpcIQAAAAAiXNlY3AyNTZrMaEDpsGvSN7oM2c04ZT9mrG32TVj-sMhb6HiKc6LMEXYEyiDdGNwgnUwg3VkcIJ1MA"

ENR Read
Sequence No: 2
Node ID: 0x5b8c..0cf7
IP: 0.0.0.0
TCP Port: 30000
UDP Port: 30000
```

(Install `enr-cli` with `cargo install enr-cli --version 0.1.0-alpha`)

**Comment by q9f** [comment]
Hi Paul, the network is not up yet and no bootnodes available.

**Comment by q9f** [comment]
I pushed 5 valid bootnodes if you want to play around with the reset Witti :)
